baseURL: "https://vashirov.blog/"
languageCode: "en-us"
title: "Viktor's blog"
theme: "PaperMod"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary
minify:
    disableXML: true
    minifyOutput: true

taxonomies:
    category: categories
    tag: tags

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
      # title: ExampleSite
      #description: "ExampleSite description"
    author: Viktor Ashirov
    # author: ["Me", "You"] # multiple authors
    #images: ["<link or path of image for opengraph, twitter-cards>"]

    defaultTheme: auto # dark, light
    disableThemeToggle: false

    ShowReadingTime: true
    ShowShareButtons: false
    disableSpecial1stPost: true
    comments: true
    hidemeta: false
    showtoc: true
    tocopen: true

    assets:
        disableHLJS: true # to disable highlight.js
        disableFingerprinting: true
        #favicon: "<link / abs url>"
        #favicon16x16: "<link / abs url>"
        #favicon32x32: "<link / abs url>"
        #apple_touch_icon: "<link / abs url>"
        #safari_pinned_tab: "<link / abs url>"

    label:
        #text: "Home"
        #icon: /apple-touch-icon.png
        #iconHeight: 35

    # profile-mode
    profileMode:
        enabled: false # needs to be explicitly set
        title: 
        subtitle: "This is subtitle"
        imageUrl: /apple-touch-icon.png
        imageWidth: 120
        imageHeight: 120
          #imageTitle: my image
        buttons:
            - name: Posts
              url: posts
            - name: Tags
              url: tags

    # home-info mode
    homeInfoParams:
      Title: "Hi there \U0001F44B"
        #Title: "Hello There"
      Content: This is a blog with random Linux, LDAP, Kubernetes/OpenShift related notes, so I don't forget things.

    socialIcons:
        - name: github
          url: "https://github.com/vashirov"
        - name: rss
          url: /index.xml


    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
menu:
    main:
        - identifier: archives
          name: Archives
          url: /archives/
          weight: 10
        - identifier: categories
          name: Categories
          url: /categories/
          weight: 20
        - identifier: tags
          name: Tags
          url: /tags/
          weight: 30
        - identifier: search
          name: Search
          url: /search/
          weight: 100
        - identifier: rss
          name: RSS
          icon: rss
          url: /index.xml
          weight: 120

permalinks:
  posts: /:year/:month/:day/:title/